# Generated by Django 3.2 on 2021-04-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_cube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cube')),
            ],
        ),
    ]
