# Generated by Django 3.2 on 2021-04-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_time_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(verbose_name='Solve Date'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.TimeField(verbose_name='Time: (HH:MM:SS.ssssss)'),
        ),
    ]
