# Generated by Django 3.2 on 2021-04-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210421_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.TimeField(),
        ),
    ]
