# Generated by Django 3.2 on 2021-04-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210422_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='stands',
            field=models.ManyToManyField(to='main_app.Stand'),
        ),
    ]
